[cron_jobs_host]
10.2.1.184 ansible_user=iccs ansible_ssh_private_key_file=~/.ssh/custom_key.pem ansible_ssh_common_args='-o ProxyJump=ec2-user@18.159.210.83 -o ForwardAgent=yes'

[bastion_host]
18.159.210.83 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/custom_key.pem

[local_machine]
localhost ansible_connection=local